repos:
  - repo: local
    hooks:
      - id: warning-signal
        verbose: true
        name: warning-signal
        entry: echo "⚠️ bypass hooks with git <command> --no-verify "
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      - id: unit-testing
        verbose: true
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
